# syntax=docker/dockerfile:1

FROM golang:1.21.3-alpine3.18

ARG PORT
ENV PORT=$PORT

WORKDIR /app
COPY . ./
WORKDIR /app/scheduler
RUN CGO_ENABLED=0 GOOS=linux go build -o /scheduler_bin
CMD ["/scheduler_bin"]
